### ISSUE TITLE
openai多调用几次会失败

### ISSUE THREAD

**Issue by jianxin88** [xielong/ai-hub#1]
openai前几次调用成功，后续多调用几次会报：HttpClientWithRetry#onRetry:35 => Retry failed with exception: java.io.IOException: Received fatal alert: handshake_failure

**Comment by xielong** [comment]
看起来像是网络或者环境问题，建议你换个时间或环境多试几次。你可以试下直接curl openai的接口是不是正常

**Comment by jianxin88** [comment]
我用的jdk11，应该是jdk自带的java.net.http.HttpClient有缺陷，我换成okhttp之后没有问题了
